<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
    <title>Montes Negros</title>
    <!-- Load jQuery -->
    <script type="text/javascript" src="http://www.google.com/jsapi"></script>
    <script type="text/javascript">
        google.load("jquery", "1");
    </script>
    <?php echo $this->headLink()->appendStylesheet('/css/main.css');
    ?>
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css" />
	<script type="text/javascript" src="/js/tinymce/jscripts/tiny_mce/jquery.tinymce.js"></script>
    <script type="text/javascript" src="http://code.jquery.com/ui/1.10.0/jquery-ui.js"></script>
	<script type="text/javascript">
        $( document ).ready(function() {
			$('.confirm_delete').click(function(e){
			var href = $(this).prop('href');
				  $( "#dialog-confirm" ).dialog({
						resizable: false,
						height:250,
						modal: true,
						buttons: {
						"Delete": function() {
							document.location = href;
						},
						Cancel: function() {
						$( this ).dialog( "close" );
						}
						}
				});
				 
				 
				return false;
			});
			
			
			
        });
    </script>

</head>

<body>
<div id="background_layer">&nbsp;</div>
<div id="container">
    <div id="allcontent">
        <header>
            <div id="header_text">
                <h1>Casa Montes Negros</h1>

                <h2>Admin Tool</h2>
            </div>

        </header>

        <div id="main_float">
            <div id="nav_float">
                <nav>
                    <ul>
                        <li class="menu_item"><a href="/admin/pages">Edit Pages</a></li>
                        <li class="menu_item"><a href="/admin/images">Edit Images</a></li>
                    </ul>
                </nav>


                <section id="main_admin"><?php echo $this->layout()->content ?>


                    <p>&nbsp;</p>

                    <p>&nbsp;</p>

                    <p>&nbsp;</p>

                    <p>&nbsp;</p>
                </section>

            </div>
        </div>

        <footer></footer>

    </div>
</div>
<div id="dialog-confirm" title="Delete item?" style="display:none;">
<p><span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>Are you sure you want to delete this item?</p>
</div>
</body>
</html>