<script type="text/javascript">
    $().ready(function () {
        $('textarea.tinymce').tinymce({
            // Location of TinyMCE script
            script_url:'/js/tinymce/jscripts/tiny_mce/tiny_mce.js',

            // General options
            theme:"advanced",
            plugins:"autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist",

            // Theme options
			//save,newdocument,
            theme_advanced_buttons1:"table,|bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
            theme_advanced_buttons2:"cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
            //   theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
            theme_advanced_toolbar_location:"top",
            theme_advanced_toolbar_align:"left",
            theme_advanced_statusbar_location:"bottom",
            theme_advanced_resizing:true,

            // Example content CSS (should be your site CSS)
            content_css:"/css/main.css",

            external_image_list_url:"/js/images",


            // Drop lists for link/image/media/template dialogs
            // template_external_list_url : "lists/template_list.js",
            //  external_link_list_url : "lists/link_list.js",
            //   external_image_list_url : "lists/image_list.js",
            //   media_external_list_url : "lists/media_list.js",

            // Replace values for the template plugin
            template_replace_values:{
                username:"Some User",
                staffid:"991234"
            }
        });
    });
</script>
<h2>Page edit</h2>

<?php
$form = $this->form;
/**
 * @var $content Application_Model_Content
 */
$content = $this->content;
$form->setAction($this->url());

if ($this->update_message) {
    echo '<p style="color:#990000;"' . $this->update_message . '</p>';
}

echo $form;
?>

<p><a href="/admin/imagegallery?url=<?php echo $content->getUrl()?>">Add images to bottom of page</a> </p>
<?php if($content->getMedia()){ ?>
<div style="position: relative">
    <?php foreach ($content->getMedia() as $image) { ?>
    <div style="float: left; position: relative;margin-right: 5px;">
        <p style="position: absolute; left: 170px; top: -10px; border-radius: 5px; border: 1px solid #010101; width: 25px; background-color: #010101; text-align: center; font-size: 15px;opacity: 0.7;"><a href="/admin/idelete?contentid=<?php echo $content->getId()?>&amp;mediaid=<?php echo $image->getId()?>&amp;url=<?php echo $content->getUrl() ?>" style="color: #FFFFFF; text-decoration: none;">X</a></p>
        <img style="" src="/<?php echo $image->getThumb()?> " alt=""/>
    </div>

    <?php } ?>
</div>
<?php } ?>
