<h2>Photo Library</h2>

<?php
$form = $this->form;
$form->setAction($this->url());
echo $form;

?>

<p>Images</p>
<div style="position: relative">
    <?php foreach ($this->images as $image) { ?>
    <div style="float: left; position: relative; margin-right: 5px; width:200px; background-color: #CCCCCC;">
        <p style="position: absolute; left: 170px; top: -10px; border-radius: 5px; border: 1px solid #010101; width: 25px; background-color: #010101; text-align: center; font-size: 15px;opacity: 0.7;"><a href="/admin/ipdelete?id=<?php echo $image->getId()?>" style="color: #FFFFFF; text-decoration: none;" class="confirm_delete">X</a></p>
        <img style="" src="/<?php echo $image->getThumb()?> " alt="" height="133"/>
  </div>

    <?php } ?>
</div>